export default {
  NEW_DEVICE: 'NEW_DEVICE',
  NEW_DEVICE_AND_NETWORK_ADDRESS: 'NEW_DEVICE_AND_NETWORK_ADDRESS',
  NEW_NETWORK_ADDRESS: 'NEW_NETWORK_ADDRESS',
  WRONG_CREDENTIALS: 'WRONG_CREDENTIALS',
  WRONG_TOKEN: 'WRONG_TOKEN',
  UNACTIVATED_USER: 'UNACTIVATED_USER',
} as const;
